export const API_ENDPOINTS = {
  USERS: `${process.env.REACT_APP_API_PREFIX}users/`,
  USER_LIST: `${process.env.REACT_APP_API_PREFIX}user-list/`,
  USER_MASTER_LIST: `${process.env.REACT_APP_API_PREFIX}get-master-list/`,
  UPDATE_MASTER_LIST: `${process.env.REACT_APP_API_PREFIX}update-master-list/`,
  EXPORT_MASTER_LIST: `${process.env.REACT_APP_API_PREFIX}export-master-list/`,
  BULK_DATA: `${process.env.REACT_APP_API_PREFIX}bulk-data/`,
  IMPORT_MASTER_LIST: `${process.env.REACT_APP_API_PREFIX}import-master-list/`,
  ASSOCIATES: `${process.env.REACT_APP_API_PREFIX}associates/`,
  FAMILY_HEAD: `${process.env.REACT_APP_API_PREFIX}family-heads/`,
  FAMILY_DETAILS: `${process.env.REACT_APP_API_PREFIX}family-details/`,
  LOGIN: `${process.env.REACT_APP_API_PREFIX}login/`,
  ADMIN_LOGIN: `${process.env.REACT_APP_API_PREFIX}admin/login/`,
  CREATE_VILLAGE: `${process.env.REACT_APP_API_PREFIX}create-village/`,
  VILLAGE_LIST: `${process.env.REACT_APP_API_PREFIX}village-list/`,
  SCREENING_REPORT: `${process.env.REACT_APP_API_PREFIX}get-screening-report/`,
  FAMILY_MEMBER_LIST: `${process.env.REACT_APP_API_PREFIX}get-family-member-list/`,
  COUNT_SUMMARY: `${process.env.REACT_APP_API_PREFIX}get-summary-count/`,
  ALL_ASSESSMENTS: `${process.env.REACT_APP_API_PREFIX}all-assessments/`,
  // Add more API endpoints as needed
};
